services:
  notification-service:
    build: .
    command: ["/app/entrypoint.sh", "app"]
    ports:
      - "8080:8080"
    profiles:
      - app
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
    env_file:
      - .env.development

  notification-service-test:
    build: .
    command: ["/app/entrypoint.sh", "test"]
    environment:
      - ENVIRONMENT=test
    volumes:
      - .:/app
    profiles:
      - test

